spring:
  rabbitmq:
    host: rabbitmq
    port: 5762
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher